### ISSUE TITLE
Antd 4.0 support

### ISSUE THREAD

**Issue by BalintBanyasz** [jannikbuschke/formik-antd#108]
Antd [4.0.0-rc.0](https://github.com/ant-design/ant-design/issues/20661) has been released and there shouldn't be any major changes before the final version becomes available.

Can we expect an updated beta or RC version of `formik-antd` as well before Ant Design 4.0 is officially released?

It would be nice to be able to test 4.0 but currently the build fails with formik-antd 1.6.3.

**Comment by jannikbuschke** [comment]
I will try to have a look at it as soon as possible, I am not sure though when I have time. Hopefully next week.
If anyone is interested to start working at this feel free to open PRs.

I expect some changes for `formik-antd` and probably a major version upgrade, however I didn't yet look what changed in antd 4.

**Comment by jannikbuschke** [comment]
I just published a version 2.0.0-beta.0 that uses v4.0.0-rc.0! Most stuff seems to work just fine. Upgrade was relatively easy but I needed to remove some types (for the different TimePickers).

Related PR  #109

**Comment by BalintBanyasz** [comment]
That's awesome! Thank you very much!

**Comment by chemicalkosek** [comment]
I made an upgrade from antd v3 to v4.  formik-antd to 2.0 beta.
Seems like some styling is not working (maybe labelCol, wrapperCol)?
The styling is ok on components where I still have antd style forms (without formik and formik-antd);

```
import { Form, Input, Radio, SubmitButton } from 'formik-antd';
import { Formik } from 'formik';

(...)

  const formItemLayout = {
    labelCol: {
      xs: { span: 24 },
      sm: { span: 8 },
    },
    wrapperCol: {
      xs: { span: 24 },
      sm: { span: 16 },
    },
  };
(...)
 <Formik
          initialValues={{ email: '', level: 'ADMIN' }}
          onSubmit= // stripped 
        >
          {() => (
            <Form>
              <Form.Item
                {...formItemLayout}
                label="E-mail (Login)"
                name="email"
                showValidateSuccess
              >
                <Input name="email" placeholder="name@mail.com" required />
              </Form.Item>
              <Form.Item {...formItemLayout} label="Poziom" name="level">
                <Radio.Group name="level">
                  {possibleLevels.map(([value, displayValue]) => (
                    <Radio.Button key={value} value={value} required>
                      {displayValue}
                    </Radio.Button>
                  ))}
                </Radio.Group>
              </Form.Item>
              <SubmitButtonContainer>
                <SubmitButton loading={loading}>
                  {loading ? 'Dodawanie' : 'Dodaj'}
                </SubmitButton>
              </SubmitButtonContainer>
            </Form>
          )}
        </Formik>

(...)

```
How it looked before antd v4 and formik-antd v2 beta (good);
![Zaznaczenie_808](https://user-images.githubusercontent.com/11018707/73854787-56804400-4833-11ea-8631-1799f7f0ca61.png)

Now (bad):
![Zaznaczenie_809](https://user-images.githubusercontent.com/11018707/73854889-86c7e280-4833-11ea-8778-e4d9228817a1.png)


deps:
```
  "@ant-design/compatible": "0.0.1-rc.1",
  "@ant-design/icons": "^4.0.0-rc.0",
  "antd": "^4.0.0-rc.3",
  "formik": "^2.1.3",
  "formik-antd": "^2.0.0-beta.1",
```

**Comment by BalintBanyasz** [comment]
I have the same issue as @chemicalkosek with `antd 4.0.0-rc.4` and `formik-antd 2.0.0-beta.1`.
Adding a fixBabelImports section in the config-overrides file (similarly to how @chemicalkosek described it for package.json) fixed it for me.
