### ISSUE TITLE
commonjs modules

### ISSUE THREAD

**Issue by n3v3rf411** [jannikbuschke/formik-antd#12]
I would like to use this project next.js but fails at importing components when rendering from server-side. Would there be no problems to change the module target from esnext to commonjs?

**Comment by jannikbuschke** [comment]
I don't see any problems but also don't have any experience with commonjs / module targets.
So in tsconfig.json changing compilerOptions.module to "commonjs" is what you propose?

**Comment by n3v3rf411** [comment]
Pardon me I also don't have thorough experience with commonjs/es6 modules. 

Something like this I guess. I tested with 7200de3553a8c02da3176892562c25f44fe600c0 and seems to be working well in next.js without resolving to using transpiler plugins like those mentioned here https://github.com/zeit/next.js/issues/706#issuecomment-451935142
```
diff --git a/tsconfig.json b/tsconfig.json
index 149d1aa..cc66934 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -2,13 +2,13 @@
   "compilerOptions": {
     "baseUrl": ".",
     "outDir": "./lib",
-    "module": "esnext",
-    "target": "es5",
+    "target": "es6",
     "lib": ["es6", "dom"],
     "sourceMap": true,
     "jsx": "react",
     "skipLibCheck": true,
     "moduleResolution": "node",
+    "esModuleInterop": true,
     "rootDir": "src",
     "forceConsistentCasingInFileNames": true,
     "noImplicitReturns": true,
```

**Comment by jannikbuschke** [comment]
I just published version 0.12 which used above compiler options. Can you give me feedback?

**Comment by n3v3rf411** [comment]
Just tested now but still the same. I think it works in my setup because I copied the code into my repository causing next.js to transpile them 🤦.

After digging in the transpiled code, I found out that it is https://github.com/jannikbuschke/formik-antd/blob/master/src/index.ts causing the problem:
```javascript
export * from "./DatePickerField";
export * from "./EnumStringEditor";
export * from "./FormikDebugField";
export * from "./InputField";
export * from "./InputNumberField";
export * from "./InputPasswordField";
export * from "./LabelField";
export * from "./SwitchField";
export * from "./TextAreaField";
export * from "./ListEditor";
export * from "./FormItem";
export * from "./DateTimeAsStringField";
export * from "./Action";
export * from "./SelectField";
export * from "./SubmitButton";
export * from "./ResetButton";
export * from "./HtmlTextField";
export * from "./CheckboxField";
//# sourceMappingURL=index.js.map
```

I checked other libraries and it looks like they are either setting tsc target to ES3 (or remove it since the default is ES3; like in https://github.com/unional/path-equal), or avoid using `export * ...` syntax (https://github.com/ant-design/ant-design)

**Comment by jannikbuschke** [comment]
@n3v3rf411 I just published version 0.13 without a target being set in tsconfig.
Can you test if it works now and give me feedback?

**Comment by n3v3rf411** [comment]
Just confirmed that 0.13.0 works with https://github.com/zeit/next.js/tree/canary/examples/with-ant-design. Thanks!
