### ISSUE TITLE
Style of Antd not working when using babel-plugin-import

### ISSUE THREAD

**Issue by MatthieuCoelho** [jannikbuschke/formik-antd#24]
Hi,
Your library is really useful however we can't use it with [babel-plugin-import](https://ant.design/docs/react/use-in-typescript) because style of antd aren't imported.

**Comment by jannikbuschke** [comment]
Do you have ideas on how to make it work?

**Comment by MatthieuCoelho** [comment]
Unfortunately no, I guess I have to include the source in my project ...

**Comment by jannikbuschke** [comment]
@CarlosGines do you have an idea how I could make use of babel imports https://ant.design/docs/react/use-in-typescript#Use-babel-plugin-import?

I guess the desired outcome is that one just import components and nowhere need to explicitly state what css is needed, the plugin would just include all css that is actually used, which would be pretty neat.

**Comment by jannikbuschke** [comment]
@MatthieuCoelho I just released preview 6 which also targets some new ecma script (es6/es2015) which uses more modern import features and might better support tree shaking scenarios and stuff.

With luck now the babel plugin could work!? not sure, but it could be worth trying againg.

**Comment by MatthieuCoelho** [comment]
It is not solved, but I don't use the babel-plugin-import anymore, I overwrite less variable with a less file directly. It is simpler and I can use formik-antd.

**Comment by RomaSto** [comment]
@MatthieuCoelho can you please provide an example?
